/**
 * Application constants – no hardcoded roles in UI; derive from API.
 */

export const ROLES = Object.freeze({
  APP_ADMINISTRATOR: "APP_ADMINISTRATOR",
  ADMIN: "ADMIN",
  ENTITY_USER: "ENTITY_USER",
  MAKER: "MAKER",
  CHECKER: "CHECKER",
  AUDITOR: "AUDITOR",
});

export const RECONCILIATION_STATUS = Object.freeze({
  OPEN: "OPEN",
  AUTO_CLOSED: "AUTO_CLOSED",
  PENDING_CHECKER: "PENDING_CHECKER",
  CLOSED: "CLOSED",
  REOPENED: "REOPENED",
});

export const ADJUSTMENT_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  PENDING_APPROVAL: "PENDING_APPROVAL",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
});

export const AUDIT_ACTIONS = Object.freeze({
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  UPLOAD_SCHEDULE: "UPLOAD_SCHEDULE",
  UPLOAD_TB: "UPLOAD_TB",
  RECONCILIATION_VIEW: "RECONCILIATION_VIEW",
  ADJUSTMENT_PROPOSE: "ADJUSTMENT_PROPOSE",
  ADJUSTMENT_APPROVE: "ADJUSTMENT_APPROVE",
  ADJUSTMENT_REJECT: "ADJUSTMENT_REJECT",
  DASHBOARD_VIEW: "DASHBOARD_VIEW",
  REPORT_EXPORT: "REPORT_EXPORT",
  MASTER_CRUD: "MASTER_CRUD",
});
